---
- name: Install and run Spring application
  hosts: backend
  become: true
  tasks:
    - name: Install dependencies and compile
      ansible.builtin.shell: mvn clean install -DskipTests=true
      args:
        chdir: /usr/src/TaskFlow_backend

    - name: Run Spring app
      ansible.builtin.shell: mvn spring-boot:run
      args:
        chdir: /usr/src/TaskFlow_backend
      async: 45
      poll: 0

- name: Install and run Angular app
  hosts: frontend
  become: true
  tags: fe
  tasks:
    - name: Install dependencies and libs
      ansible.builtin.shell: source ~/.nvm/nvm.sh && npm install --loglevel=error        
      args:
        chdir: /usr/src/TaskFlow_frontend
        executable: /bin/bash
      become: true


    - name: Run Angular app
      ansible.builtin.shell: source ~/.nvm/nvm.sh && npm run start
      args:
        chdir: /usr/src/TaskFlow_frontend
      async: 30
      poll: 0